apiVersion: v1
kind: Pod
metadata:
  name: lcchua-flask-app
  labels:
    app: lcchua-ecr-hello
spec:
  containers:
    - name: lcchua-flask-app
      image: public.ecr.aws/u2q1a2y8/lcchua-flask-app:v2
      ports:
        - containerPort: 8000
