apiVersion: v1
kind: Pod
metadata:
  name: lcchua-flask-app
  labels:
    app: lcchua-ecr-hello
spec:
  containers:
    - name: lcchua-flask-app
      image: public.ecr.aws/u2q1a2y8/lcchua-flask-app:v1
      ports:
        - containerPort: 8000
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
